### ISSUE TITLE
Cannot find the device specified

### ISSUE THREAD

**Issue by jtara1** [rsxdalv/albion-trader#4]
Before I was getting an error: `device must be a string`, but after attempting to fix I get this error.

```
C:\Users\James\Documents\_Github-Projects\albion-trader\index.js:21
    linkType = cap.open(String(device), filter, bufSize, buffer);
                   ^

Error: Error opening adapter: The system cannot find the device specified. (20)
    at C:\Users\James\Documents\_Github-Projects\albion-trader\index.js:21:20
    at C:\Users\James\Documents\_Github-Projects\albion-trader\node_modules\network\lib\index.js:109:11
    at C:\Users\James\Documents\_Github-Projects\albion-trader\node_modules\network\lib\win32.js:15:7
    at Object.callback (C:\Users\James\Documents\_Github-Projects\albion-trader\node_modules\wmic\index.js:244:7)
    at C:\Users\James\Documents\_Github-Projects\albion-trader\node_modules\wmic\node_modules\async\dist\async.js:1312:26
    at C:\Users\James\Documents\_Github-Projects\albion-trader\node_modules\wmic\node_modules\async\dist\async.js:323:20
    at C:\Users\James\Documents\_Github-Projects\albion-trader\node_modules\wmic\index.js:219:9
    at err (C:\Users\James\Documents\_Github-Projects\albion-trader\node_modules\wmic\node_modules\async\dist\async.js:2939:19)
    at wrapper (C:\Users\James\Documents\_Github-Projects\albion-trader\node_modules\wmic\node_modules\async\dist\async.js:270:20)
    at iteratorCallback (C:\Users\James\Documents\_Github-Projects\albion-trader\node_modules\wmic\node_modules\async\dist\async.js:497:17)

Process finished with exit code 1
```

**Comment by rsxdalv** [comment]
My guess is that 'device' is undefined since the most common network
interface isn't present on your computer. The device finder needs to be
changed to incorporate your network device.

**Comment by jtara1** [comment]
I noticed npcap is a dep of npm networks, a dependency of this project

https://www.npmjs.com/package/cap

**Comment by rsxdalv** [comment]
I see. Can that help solve the problem?

**Comment by jtara1** [comment]
no, not by just installing it
